### ISSUE TITLE
Split roles into multiple repositories

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/ansible-role-grsecurity#109]
This git repository contains three separate roles:

* build-grsec-kernel
* build-grsec-metapackage
* install-grsec-kernel

The primary use of this repository is to publish the kernel maintenance documentation for use with [SecureDrop](https://github.com/freedomofpress/securedrop). Some of the roles and associated playbooks are specifically intended for use with SecureDrop, e.g. `build-grsec-metapackage`, but the others are more generalized.

Most of the Ansible logic required to maintain SecureDrop exists in the SecureDrop repository—except the kernel build information. If we split up these roles, we can selectively include them in the SecureDrop repository, which should make the documentation story more straightforward for future (and current) maintainers.

**Comment by conorsch** [comment]
A more intuitive role breakdown:

* freedomofpress.grsecurity-build
* freedomofpress.grsecurity-install 

The metapackage role can leverage https://github.com/freedomofpress/ansible-role-build-debian-package specifically for the SecureDrop use case.

**Comment by conorsch** [comment]
Made progress, have two broken out roles in separate repositories now:

* https://github.com/freedomofpress/ansible-role-grsecurity-build
* https://github.com/freedomofpress/ansible-role-grsecurity-install

Porting over the metapackage logic will require integration with another role as mentioned above. This repo can remain to house documentation on building SecureDrop-specific kernels from source. Beefing up the dev environment via Molecule will provide endpoints for all the "example" playbooks, and we can include the external roles via dependencies now.

**Comment by conorsch** [comment]
The final role logic, that for the `securedrop-grsec` metapackage, was broken out of this repo and consolidated into the SecureDrop repository in https://github.com/freedomofpress/securedrop/issues/2696 . There's still a bit of housekeeping to be done on this repository, such as updating the README to link out to the old roles. That's the last task.

**Comment by eloquence** [comment]
We now use a dockerized setup, https://github.com/freedomofpress/kernel-builder/ . Closing and archiving this repo.
