### ISSUE TITLE
Support targeting multiple hosting platforms

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/ansible-role-grsecurity#19]
In the context of SecureDrop, we prohibit hosting on cloud servers, due to the insecurity of allowing third-parties access to the virtualized environment. In the context of general web infrastructure, however, running a grsecurity-hardened kernel on cloud instances has a lot of benefits. We should consider supporting:
- [x] aws
- [x] digitalocean
- [ ] gandi
- [ ] linode

It will be simplest and safest to provide a base config for each provider, with the relevant grsecurity options enabled via `make menuconfig`. Therefore the logic surrounding `grsecurity_build_strategy` should be simplified, allowing admins to target a provider and build accordingly. The strategy should default to `manual`, requiring an admin to run `make menuconfig` themselves to ensure a stable build. At the role or playbook level, the build strategy can be overridden to target certain platforms.

The build strategy should be embedded in the filename, as well, to avoid confusion when building for disparate hosts.

**Comment by garrettr** [comment]
I think this could be a game-changer for more widespread grsecurity adoption :8ball:

**Comment by conorsch** [comment]
The build role works well on both DigitalOcean and AWS, i.e. the major cloud providers. No plans at this time to implement first-class support for Linode or Gandi, but building for those should be trivial given the support for custom config files via #68. Therefore closing.
