### ISSUE TITLE
paxctld integration

### ISSUE THREAD

**Issue by ageis** [freedomofpress/ansible-role-grsecurity#38]
The `install-grsec-kernel` role should eventually handle configuration of persistent PaX flags for specified binaries via the paxctld daemon.

**Comment by ageis** [comment]
Closing this issue as we now have a `paxctld` role in our private infrastructure repo.

**Comment by conorsch** [comment]
@ageis Reopening this issue to track adding the paxctld role as a dependency for the grsec-install role. Otherwise upgrading from one version of grsecurity to the next may cause GRUB problems.

**Comment by conorsch** [comment]
We have a separate role for paxctld: https://github.com/freedomofpress/ansible-role-paxctld but it's yet to be included as a dependency in this project.

**Comment by conorsch** [comment]
Let's leave the paxctld role separate. This repo already contains three separate roles, and I'd rather move toward breaking them apart than shoehorning more roles into one repo.
