### ISSUE TITLE
Handle special group creation

### ISSUE THREAD

**Issue by ageis** [freedomofpress/ansible-role-grsecurity#41]
Defined groups are needed for three grsecurity features that we haven't explored fully: /proc restriction, TPE (trusted path execution), and socket restrictions.

The default special groups are as follows and are used regardless of whether they exist yet:
- (1001) GID exempted from /proc restrictions
- (1005) GID for TPE-untrusted users
- (1006) GID for users with kernel-enforced SymlinksIfOwnerMatch

Debian does the following:

```
    addgroup --gid 64040 --system --quiet grsec-tpe ||true
    addgroup --gid 64041 --system --quiet grsec-sock-all ||true
    addgroup --gid 64042 --system --quiet grsec-sock-clt ||true
    addgroup --gid 64043 --system --quiet grsec-sock-srv ||true
    addgroup --gid 64044 --system --quiet grsec-proc ||true
```

Coldkernel does this:

```
sudo groupadd -g 9001 grsecproc
sudo groupadd -g 9002 tpeuntrusted
sudo groupadd -g 9003 denysockets
```

Eventually further down the line when we start leveraging such features more we need to handle creating these special groups. In particular it's an unintended (though unimportant) security hole that GID 1001 is currently exempted from /proc restriction (which is enabled in the default automatic configuration). Ideally it should be set to something else that won't match a user.

**Comment by conorsch** [comment]
Difficult to do well in a DRY fashion given that these values can be altered in the build role via kernel config options:

```
$ grep GID files/config-digitalocean
CONFIG_GRKERNSEC_PROC_GID=1001
CONFIG_GRKERNSEC_TPE_UNTRUSTED_GID=1005
CONFIG_GRKERNSEC_SYMLINKOWN_GID=1006
CONFIG_GRKERNSEC_TPE_GID=1005
```

and the install role must match. I'm inclined to say that admins using these features should configure groups at the play-level via custom tasks in a site-specific playbook, but would entertain a PR that resolved with an empty dict mapping (a similar approach would work very well for #39).
