### ISSUE TITLE
Edge case xz --decompress bug on "Extract Linux tarball (.tar -> directory)" task

### ISSUE THREAD

**Issue by ghost** [freedomofpress/ansible-role-grsecurity#49]
This is with ansible 1.9.2 so I might just need to upgrade. Posting this because I still want to run this playbook as one of many roles in a playbook. 

I believe I have found an ansible related bug in a command in this playbook but I am unsure on how to debug deeper. 

This does **not** impact the full playbook you provide.

I have been working on a fork to make a generic grsec role so as to to add it to pre-existing machines or vagrant dev machines.

What I have done so far: extracted the playbooks for "build-grsec-kernel" "build-grsec-metapackage" and "install-grsec-kernel" added the files build-grsecurity-kernel-test.yml/install-grsecurity-kernel.yml into the playbook root and changed the hosts: grsec-install to all. 

In my playbook I have set the order of execution of the plays as:

```
- name: build grsec
  include: roles/grsec/build-grsecurity-kernel-test.yml
- name: install grsec
  include: roles/grsec/install-grsecurity-kernel.yml
```

Is there a better way to do this as this method causes me a lot of failures?

(unrelated bug I have not thus far been able to get to work correctly as a role and that is not the purpose of this issue).

The error message is:

```
TASK: [build-grsec-kernel | Extract Linux tarball (.tar -> directory).] ******* 
changed: [default] => {"changed": true, "check_results": {"cmd": "/bin/tar -C \"/usr/local/src\" --diff -f \"/usr/local/src/linux-4.4.4.tar\"", "err": "/bin/tar: linux-4.4.4: Warning: Cannot stat: No such file or directory\n/bin/tar: linux-4.4.4/.get_maintainer.ignore: Warning: Cannot stat: No such file or directory\n/bin/tar
```

this continues for every file in the linux-4.4.4 directory.

In order for me to solve this problem I modified the "xz --decompress" command and use "unxz" instead and that effectively bypassed the issue. In previous ansible playbooks I worked on I found that the command module for whatever reason has a tendency to mess up with alphanumeric characters (even while quoted).

With my change above I get the desired result:

TASK: [build-grsec-kernel | Extract Linux tarball (.xz -> .tar).] ************\* 
changed: [default] => {"changed": true, "cmd": ["unxz", "/usr/local/src/linux-4.4.5.tar.xz"], "delta": "0:00:10.621326", "end": "2016-03-11 04:58:21.955393", "rc": 0, "start": "2016-03-11 04:58:11.334067", "stderr": "", "stdout": "", "warnings": []}

Additionally, the following play also fails in this setup: "Extract Linux tarball (.tar -> directory)".

With which manually changing to command tar gets past.

The last error which I'm now giving up on solving is:

TASK: [install-grsec-kernel | Install grsecurity-patched kernel deb package.] **\* 
failed: [default] => {"failed": true, "parsed": false}
BECOME-SUCCESS-zsmccdpktxieywucqbxaqcxjqrlrzfyb
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1457676639.85-211174664282747/apt", line 2246, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1457676639.85-211174664282747/apt", line 602, in main
    force=force_yes, dpkg_options=p['dpkg_options'])
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1457676639.85-211174664282747/apt", line 369, in install_deb
    m.fail_json(msg="Error: %s\nSystem Error: %s" % (pkg._failure_string,str(e)))
UnboundLocalError: local variable 'pkg' referenced before assignment

and none of the grsec kernel deb files can be found.

**Comment by ghost** [comment]
Trying ansible 2.1.0 fixes these errors but the playbook fails on 

```
TASK [roles/grsec/install-grsec-kernel : Copy kernel image deb package.] *******
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "could not find src=/home/a/grsec/linux-image-4.4.5-grsec_10.00.manual_amd64.deb"}
```

which looks like it is trying to use my home directory to find the file instead of from within the vagrant which is unexpected behavior, still looking.

**Comment by conorsch** [comment]
> which looks like it is trying to use my home directory

That's almost surely related to a variable name collision for `grsecurity_deb_package`. See #50 for explanation. In short, the build and install roles both use that var, but handle them differently. #45 and #50 solve the issue by splitting the var into:
- `grsecurity_install_deb_package` # filepath to .deb on Ansible controller
- `grsecurity_build_deb_package` # filename of .deb on build host, for fetching back to Ansible controller

As for your original issue, let me try rolling back to Ansible 1.9.2 and see if I can reproduce. I'm seriously considering requiring Ansible v2 to use this role (and others we maintain), since it would vastly simplify things. Happy to have a conversation if a v2 requirement would be prohibitive for you.

**Comment by ghost** [comment]
Great I will take a look into those in a bit. I'm fine with the 2.0 requirement, I just tend to lag behind ansible releases due to a history of buggy releases. The ansible version of 1.9.2 I was using was based on the brew default for OSX.

**Comment by conorsch** [comment]
> I just tend to lag behind ansible releases due to a history of buggy releases.

Heard. I'm finally using v2 as standard across most projects now, due to the minor releases that smoothed over much of the migration pain.

**Comment by ghost** [comment]
Yeah that is definitely it. I also have the bizarre behavior that running "vagrant up" will have a new file produced called  "site-vagrant.retry" with only "default" inside of it.

So on my current setup:

```
- roles/grsec/build-grsec-metapackage
- roles/grsec/build-grsec-kernel
```

these two work and this one:

```
- roles/grsec/install-grsec-kernel
```

makes:

```
TASK [roles/grsec/install-grsec-kernel : Copy kernel image deb package.] *******
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "could not find src=/Users/a/missedgy/exodus-ansibleplay/linux-image-4.4.5-grsec_10.00.manual_amd64.deb"}
```

perhaps grsecurity_deb_package can be refactored as grsecurity_build_deb_package and grsecurity_install_deb_package?

**Comment by conorsch** [comment]
> perhaps grsecurity_deb_package can be refactored as grsecurity_build_deb_package and grsecurity_install_deb_package?

You hit it on the nose! See #50 for an implementation of this solution.

**Comment by ghost** [comment]
Closing  this for #50.
