### ISSUE TITLE
pax flags for applications?

### ISSUE THREAD

**Issue by ghost** [freedomofpress/ansible-role-grsecurity#52]
Hey there,

I have been working on compiling a list of required pax flags needed to get applications to work post install, do you have a similar list that you could add to this role?

**Comment by ageis** [comment]
@Andrew415 hey there, we currently have a separate paxctld role for managing PaX flags: https://github.com/freedomofpress/ansible-role-paxctld You can use that if you like and add them to the `defaults/main.yml`.

**Comment by conorsch** [comment]
We're dogfooding the paxctld role internally and have had great results so far—make sure to set `grsecurity_install_set_paxctl_flags: false` if you plan to try it out. Eventually it'll probably be listed as a dependency for the install role, and the `paxctl` commands removed completely.

**Comment by conorsch** [comment]
Closing in favor of #38.
