### ISSUE TITLE
Use QEMU to emulate CPU of recommended SD hardware

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/ansible-role-grsecurity#88]
Brought up first in https://github.com/freedomofpress/ansible-role-grsecurity/pull/85#issuecomment-266611369, we should investigate modifying our `Vagrantfile` to instruct QEMU to emulate the processors of recommended SD hardware (currently some Intel NUC model). One thing to consider is that this has the potential to slow down compilation, so maybe it's best we reserve this for use in the `grsec-install` machine (we should also consider using it for for `app-prod` and `app-mon` in SD). On that note, it would be good to investigate if Vagrant chooses the fastest reliable CPU option by default.

**Comment by conorsch** [comment]
We're investigating more hardware options for SecureDrop (https://github.com/freedomofpress/securedrop/issues/1432), so restricting the emulation would not be a good idea to ensure broad-based support. If we do decide to implement hardware emulation in virtualization, that's best done in the SecureDrop repository (https://github.com/freedomofpress/securedrop).
